In [1]:
import numpy as np
import pandas as pd
from data_prep import *
import os
from pandas.tseries.offsets import DateOffset, Week
from data_extractor import *

In [2]:
df = pd.read_csv(os.path.join(os.getcwd(),'Data/master_data.csv'))
df = df.drop(columns=['4 weeks coupon equivalent','8 weeks coupon equivalent', '13 weeks coupon equivalent',
                      '17 weeks coupon equivalent', '26 weeks coupon equivalent','52 weeks coupon equivalent',
                      'BidImpliedVolatility','AskImpliedVolatility'])
df = df.drop_duplicates()

In [3]:
data_ext = DataExtractor(df,interpolator='linear')
ddt = data_ext.extract_data(expiry_in_months=6,moneyness=90,callput='p',hold=6,bot=1,symbool='SP',end_date=20101005)
ddt.AdjExpiry

0    2010-07-16
1    2010-08-20
2    2010-10-15
3    2010-10-15
4    2010-11-26
5    2011-01-21
6    2011-01-21
7    2011-02-25
8    2011-04-15
Name: AdjExpiry, dtype: object

In [12]:
df[(df.AdjExpiry ==data.AdjExpiry.values[0])&(df.CallPut==data.CallPut.values[0])&(df.AdjStrike==data.AdjStrike.values[0])&(df.Symbol==data.Symbol.values[0])][['TradeDate','AskPrice','BidPrice']]

      TradeDate  AskPrice  BidPrice
5364   20100715     0.019     0.019
6501   20100819     0.000     0.000

In [5]:
data =ddt[ddt.index==1]
data

,Ticker,TradeDate,ExpiryDate,CallPut,AdjStrike,Strike,AdjSpot,Spot,Month_To_Expiry,days_to_expiry,...,Theta,Rho,FmtTradeDate,FmtExpiryDate,risk_free_rate_4,risk_free_rate_8,risk_free_rate_13,risk_free_rate_17,risk_free_rate_26,risk_free_rate_52
1,AAPL,20100218,20100820,p,6.61,320.0,7.25,202.93,6,183,...,-0.001605,-0.012878,2010-02-18,2010-08-21,0.0007,NaN,0.001,NaN,0.001799,0.003594

In [6]:
ddd = data_ext.hold_options(data,6,20101005)
ddd[0]

1
1 20100218
1 20100318
1 20100422
1 20100520
1 20100617
3 20100715
1 20100819

,Ticker,TradeDate,ExpiryDate,CallPut,AdjStrike,Strike,AdjSpot,Spot,Month_To_Expiry,days_to_expiry,...,FmtTradeDate,FmtExpiryDate,risk_free_rate_4,risk_free_rate_8,risk_free_rate_13,risk_free_rate_17,risk_free_rate_26,risk_free_rate_52,Gama,Flag
0,AAPL,20100218,20100820,p,6.61,320.0,7.25,202.93,6,183,...,2010-02-18,2010-08-21,0.0007,NaN,0.0010,NaN,0.001799,0.003594,0.21,1
1,AAPL,20100318,20100820,p,6.61,320.0,8.02,202.93,5,155,...,2010-02-18,2010-08-21,0.0007,NaN,0.0010,NaN,0.001799,0.003594,0.14,1
2,AAPL,20100422,20100820,p,6.61,320.0,9.52,202.93,4,120,...,2010-02-18,2010-08-21,0.0007,NaN,0.0010,NaN,0.001799,0.003594,0.02,1
3,AAPL,20100520,20100820,p,6.61,320.0,8.49,202.93,3,92,...,2010-02-18,2010-08-21,0.0007,NaN,0.0010,NaN,0.001799,0.003594,0.10,1
4,AAPL,20100617,20100820,p,6.61,320.0,9.71,202.93,2,64,...,2010-02-18,2010-08-21,0.0007,NaN,0.0010,NaN,0.001799,0.003594,0.00,1
5,AAPL,20100715,20100821,p,6.61,185.0,8.98,251.45,1,37,...,2010-07-15,2010-08-21,0.0016,NaN,0.0015,NaN,0.001999,0.002597,NaN,0
6,AAPL,20100819,20100820,p,6.61,320.0,8.92,202.93,0,1,...,2010-02-18,2010-08-21,0.0007,NaN,0.0010,NaN,0.001799,0.003594,0.00,1

In [10]:
ddd[0][['TradeDate','AskPrice','BidPrice']]

   TradeDate  AskPrice  BidPrice
0   20100218  0.372275  0.372275
1   20100318  0.088264  0.088264
2   20100422  0.005208  0.005208
3   20100520  0.095529  0.095529
4   20100617  0.009000  0.009000
5   20100715  0.019000  0.019000
6   20100819  0.003000  0.003000

In [14]:
(0.003000-0.019000)/0.019000

-0.8421052631578948

In [4]:
df_opt=extract_data(df,expiry_in_months=12,callput='c',moneyness=110,hold=12,bot=3,start_date = 20130628)

NameError: name 'extract_data' is not defined

In [ ]:
df.columns

In [ ]:
df.columns

In [ ]:
df_opt.drop(columns=['Ticker','FmtTradeDate','risk_free_rate_4', 'risk_free_rate_8', 'risk_free_rate_13','risk_free_rate_17', 'risk_free_rate_26', 'risk_free_rate_52']).head()

In [ ]:
df_opt[df_opt.days_to_expiry==350]

In [ ]:
target = pd.to_datetime(20130628, format="%Y%m%d") + DateOffset(months=12)
s = pd.to_datetime(df.AdjExpiry.unique())
s = s[(s.year >= target.year)&(s.month>=target.month)]
str(s.min().date())

In [ ]:
def get_days(date,months,s1,s2):
    
    '''
    date: trade date
    months : expected months to exp
    s : sorted expiry dates of of the available options on the above trade date
     '''
    
    trade_date = pd.to_datetime(date, format="%Y%m%d")
    target = trade_date + DateOffset(months=months-1)
    exp = s1[s1 >= target]
    if exp.empty:
        target = trade_date + DateOffset(months=months)
        exp = s2[s2 >= target]
    expiry = exp.min()
    days_to_expiry = (expiry - trade_date).days    
    days_to_expiry = (exp.min()-pd.to_datetime(date, format="%Y%m%d")).days

    # safety check
    if days_to_expiry > months * 30 + 60:
        target = trade_date + DateOffset(months=months)
        exp = s2[s2 >= target]
        expiry = exp.min()
        days_to_expiry = (expiry - trade_date).days

    return days_to_expiry, str(expiry.date())

In [ ]:
def get_days(date,months,s):
    
    
    target = pd.to_datetime(date, format="%Y%m%d") + DateOffset(months=months)
    mask = (s.year >= target.year)
    exp = s[mask]    
    days_to_expiry = (exp.min()-pd.to_datetime(date, format="%Y%m%d")).days
    
    dt = str(exp.min().date())
    return days_to_expiry,dt

In [ ]:
df = pd.read_csv(os.path.join(os.getcwd(),'Data/master_data.csv'))
df = df.drop(columns=['4 weeks coupon equivalent','8 weeks coupon equivalent', '13 weeks coupon equivalent',
                      '17 weeks coupon equivalent', '26 weeks coupon equivalent','52 weeks coupon equivalent',
                      'BidImpliedVolatility','AskImpliedVolatility'])

In [ ]:
def check_moneyness(df_trade, moneyness):
    
    idx = (df_trade['AbsMoneyness'] - moneyness).abs().idxmin()
    mn = df_trade.AbsMoneyness.loc[idx]
    df_trade = df_trade[df_trade.AbsMoneyness==mn]
    return df_trade

In [ ]:
def extract_data(df,expiry_in_months = 3,moneyness = 90,callput = 'c',hold=1,bot=1,symbool = 'EV',interpolator = 'bicubic',start_date = None,end_date= None,test=False):
    dates = np.sort(df[df.Symbol == symbool].TradeDate.unique())
    if start_date:
        dates = dates[dates>=start_date]
    if end_date:
        dates = dates[dates<=end_date]


    opt_list = []
    for i in range(0,len(dates),bot):
        flag = False
        date = dates[i]
        if i+hold<len(dates-1):
            last_trade = dates[i+hold]
        else:
            last_trade = dates[-1]
        d1 = pd.to_datetime(dates[i], format="%Y%m%d")
        d2 = pd.to_datetime(last_trade, format="%Y%m%d")
        days = (d2 - d1).days
        

        if df[(df.Month_To_Expiry==expiry_in_months)&(df.TradeDate==date)&(df.CallPut ==callput)&(df.days_to_expiry>=days)].shape[0]>=1:
            df_trade = df[(df.Month_To_Expiry==expiry_in_months)&(df.TradeDate==date)&(df.CallPut ==callput)&(df.days_to_expiry>=days)]

            if df_trade[(df_trade.Moneyness==moneyness)].shape[0]>=1:
                df_trade = df_trade[df_trade.Moneyness==moneyness]

            else:
                df_trade = check_moneyness(df_trade, moneyness,expiry_in_months)
            days_valid = df_trade.days_to_expiry.min()

        elif df[(df.Month_To_Expiry==expiry_in_months)&(df.TradeDate==date)&(df.CallPut ==callput)&(df.days_to_expiry<days)].shape[0]>=1:
            df_trade = df[(df.Month_To_Expiry==expiry_in_months)&(df.TradeDate==date)&(df.CallPut ==callput)&(df.days_to_expiry<days)]
            if df_trade[(df_trade.Moneyness==moneyness)].shape[0]>=1:
                df_trade = df_trade[df_trade.Moneyness==moneyness]

            else:
                df_trade = check_moneyness(df_trade, moneyness,expiry_in_months)
            days_valid = df_trade.days_to_expiry.max()

        else:
            fl = True
            add_factor =1
            while fl:
                df_trade = df[(df.TradeDate==date)&(df.CallPut ==callput)&(df.days_to_expiry>=days)&
                            (df.Month_To_Expiry==expiry_in_months+add_factor)]
                if df_trade.shape[0]>=1:
                    
                    if df_trade[df_trade.Moneyness==moneyness].shape[0]>=1:
                        df_trade = df_trade[df_trade.Moneyness==moneyness]
                    else:
                        df_trade = check_moneyness(df_trade, moneyness,expiry_in_months+1)
                    days_valid = df_trade.days_to_expiry.min()

                else:
                    add_factor+=1
                if df_trade.shape[0]>=1 or add_factor>1:
                    fl = False
                
                if not fl and df_trade.shape[0]==0 :
                    data = extract_clean_data(df,flag = callput,trade_date=date)
                    surface_genrator = GenSurface(data,interpolator=interpolator)
                    surface_genrator.update_surface()
                    # print(date)
                    fwd_mnyness = surface_genrator.fwd_moneyness()
                    x,y= surface_genrator.known_data()
                    surface_genrator.gen_spline()
                    # surface_genrator.abs_error(x,y,z)
                    adj_spot = df[df.TradeDate==date].AdjSpot.iloc[0]
                    days_to_expiry,exp_date = get_days(date,expiry_in_months,pd.to_datetime(x,format="%Y%m%d").unique(),pd.to_datetime(df.AdjExpiry).unique())
                    exp_list =exp_date.split('-')
                
                    
                    adj_expiry = df[df.AdjExpiry==exp_date].iloc[0].AdjExpiry
                    fmtexpdt = df[df.AdjExpiry==exp_date].iloc[0].FmtExpiryDate
                    expspot = df[df.AdjExpiry==exp_date].iloc[0].ExpirySpot
                    x = df[df.TradeDate==date].iloc[0]
                    x.loc['days_to_expiry']=days_to_expiry
                    risk_free_rate = compute_risk_free_rate(x)
                    available_strikes = np.sort(np.unique(y))
                    stk = available_strikes[np.abs(available_strikes-(moneyness*adj_spot/100)).argmin()]
                    exp_date =''
                    for i in exp_list:
                        exp_date+=i
                    exp_date = int(exp_date)
                    # print(exp_date)

                    px,delta,gama,vega,theta,rho = surface_genrator.compute_px(callput,adj_spot,days_to_expiry,risk_free_rate,stk)
                    df_trade = df[df.TradeDate==date].head(1)
                    df_trade.AdjStrike = stk
                    df_trade.ExpiryDate = exp_date
                    df_trade.AdjExpiry = adj_expiry
                    df_trade.AskPrice = px
                    df_trade.BidPrice = px
                    df_trade.CallPut = callput
                    df_trade.Symbool = symbool
                    df_trade.Delta = delta
                    df_trade.Gama = gama
                    df_trade.Vega = vega
                    df_trade.Theta = theta
                    df_trade.Rho = rho
                    df_trade.days_to_expiry = days_to_expiry
                    df_trade.Month_To_Expiry = expiry_in_months
                    df_trade.Moneyness = moneyness
                    df_trade.AbsMoneyness = stk/adj_spot
                    df_trade.ExpirySpot = expspot
                    df_trade.FmtExpiryDate = fmtexpdt
                    flag = True
                                


                    

                else:
                    if test:
                        print(f'Data with moneyness={moneyness},{callput} and expiry in {expiry_in_months} months not traded on {date} checking with expiry in months+={add_factor}')
     
        # max_oi = df_trade.OpenInterest.max()
        if not flag:
            df_trade = df_trade[df_trade.days_to_expiry==days_valid]
            if df_trade.shape[0]>1:
                idx = (df_trade['AbsMoneyness'] - moneyness).abs().idxmin()
                mn = df_trade.AbsMoneyness.loc[idx]
                df_trade = df_trade[df_trade.AbsMoneyness==mn]
            
        opt_list.append(df_trade)


        
    df_opt  = pd.concat(opt_list, ignore_index=True)

    return df_opt

In [ ]:
df_opt=extract_data(df,expiry_in_months=12,callput='p',moneyness=110,hold=12,bot=3,start_date = 20130628)

In [ ]:
df_opt

In [ ]:
def get_next(x):
    """
    get the next trade date and check if the option was traded in that date"""
    dates = np.sort(df[df.Symbol == 'EV'].TradeDate.unique())
    
    trade_date = x.BotDate
    idx = np.where(dates==trade_date)[0][0]
   
    if idx == len(dates)-1:
        
        return (True,trade_date)
    
    date = dates[idx+1]
    return (date in x.TradeDate,date)

In [ ]:
def check_for_dates(df,expiry_in_months=1,callput='c',moneyness=100):   
    df_opt=extract_data(df,expiry_in_months=expiry_in_months,callput=callput,moneyness=moneyness)
    
    bot = []
    trade_date = []
    strike = []
    expiry = []
    next_date =[]
    for i in range(len(df_opt)):
        
        data = df_opt.loc[i]

        bot.append(data.TradeDate)
        strike.append(data.AdjStrike)
        expiry.append(data.AdjExpiry)
        trade_date.append(df[(df.AdjStrike == data.AdjStrike)&(df.ExpiryDate == data.ExpiryDate)&(df.Symbol=='EV')
                            &(df.CallPut ==data.CallPut)&(df.TradeDate>data.TradeDate)].TradeDate.values)
    trade_summary = pd.DataFrame({'BotDate':bot,'TradeDate':trade_date,'Strike':strike,'Expiry':expiry})
    trade_summary['traded_dates'] = trade_summary.apply(lambda x:get_next(x),axis=1)
    trade_summary['Traded'] = trade_summary.traded_dates.apply(lambda x : x[0])
    trade_summary['TradeDate'] = trade_summary.traded_dates.apply(lambda x : x[1])
    trade_summary = trade_summary[trade_summary.Traded==False]
    trade_summary = trade_summary.drop(columns=['traded_dates'])
    return trade_summary

In [ ]:
check_for_dates(df,expiry_in_months=3,callput='c',moneyness=90)

In [ ]:
df[(df.TradeDate==20101029)&(df.CallPut=='c')&(df.AdjStrike==9.64)]

In [ ]:
trade_dict = {'100_1m_c':(1,'c',100),'90_3m_p':(3,'p',90),'110_3m_c':(3,'c',110)}
for k,v in trade_dict.items():

    trade_dict[k] = check_for_dates(df,expiry_in_months=v[0],callput=v[1],moneyness=v[2])

In [ ]:
trade_dict['100_1m_c']

In [ ]:
trade_dict['90_3m_p']

In [ ]:
df[(df.TradeDate==20200831)&(df.ExpiryDate==20201016)&(df.Month_To_Expiry==2)&(df.CallPut =='p')&(df.Strike==round(385/4,2))]

In [ ]:
df[(df.ExpiryDate==20140816)&(df.CallPut =="p")&(df.Strike==540)]

In [ ]:
df[(df.ExpiryDate==20140816)&(df.CallPut =="p")&(df.Strike==77.14)]

In [ ]:
df_opt.tail()

In [ ]:
df[(df.ExpiryDate ==20100417)&(df.CallPut=='c')&(df.Strike==180)&(df.Symbol=='EV')]

In [ ]:
df[(df.ExpiryDate ==20100417)&(df.CallPut=='c')&(df.Strike==180)&(df.Symbol=='EV')].BidPrice

In [ ]:
def compute_delta_iv(x):
    df_iv = df[(df.ExpiryDate ==x['ExpiryDate'])&(df.CallPut==x['CallPut'])&(df.Strike==x['Strike'])&(df.Symbol=='EV')]
    dates = np.sort(df[df.Symbol == 'EV'].TradeDate.unique())
    idx = np.where(dates==x['TradeDate'])[0][0]
    if dates[idx]== dates[-1]:
        trade_date = dates[idx]
    else:
        trade_date = dates[idx+1]

    if trade_date in df_iv.TradeDate:
        if trade_date == dates[-1]:
            delta_iv = 0
        else:
            delta_iv = df_iv[df_iv.Tradedate == trade_date].IV - x.IV
    

    else:
        delta_iv = 0
    return delta_iv

In [ ]:
df[(df.CallPut=='c')&(df.Strike==90)&(df.ExpiryDate==20110122)&(df.TradeDate==20100129)].Strike.values[0]

In [ ]:
def get_premium(df,flag,stk,date,exp_date,interpolator = 'bicubic'):
    data = extract_clean_data(df,flag = flag,trade_date=date)
    surface_genrator = GenSurface(data,interpolator=interpolator)
    surface_genrator.update_surface()
    # print(date)
    fwd_mnyness = surface_genrator.fwd_moneyness()
    x,y= surface_genrator.known_data()
    surface_genrator.gen_spline()
    # surface_genrator.abs_error(x,y,z)
    adj_spot = df[df.TradeDate==date].AdjSpot.iloc[0]
    # print(exp_date)
    days_to_expiry = (pd.to_datetime(exp_date,format="%Y%m%d")-pd.to_datetime(date, format="%Y%m%d")).days
    # print("days",days_to_expiry)
    x = df[df.TradeDate==date].iloc[0]
    x.loc['days_to_expiry']=days_to_expiry
    risk_free_rate = compute_risk_free_rate(x)
    px,delta,gama,vega,theta,rho = surface_genrator.compute_px(flag,adj_spot,days_to_expiry,risk_free_rate,stk)
    return px,delta

In [ ]:
def compute_contracts(x,df_cnt,capital):
    spot = x.SpotStart
    tradedate = x.TradeStart
    contracts = capital/(spot*df_cnt.loc[df_cnt.TradeStart==tradedate,'ActiveOptions'].values[0])
    
    return contracts

In [ ]:
def compute_pnl(data,hold,mt,interpolator = 'bicubic'):
    BotOn=[]
    TradeDate = []
    Exp = []
    StrikeBot = []
    SpotStart = []
    Spot = []
    OptPxBot = []
    OptPxTrade = []
    OptDelta = []
    SpotPct = []
    OptPnl = []
    SpotExp = []
    TradeStart = []
    Synth = []
    f1 = 0
    df_iv = df[(df.AdjExpiry ==data.AdjExpiry.values[0])&(df.CallPut==data.CallPut.values[0])&(df.AdjStrike==data.AdjStrike.values[0])&(df.Symbol==data.Symbol.values[0])]
    
    if len(df_iv)==0:
         df_iv = data
         f1 = 1
        
    dates = np.sort(df[df.Symbol == data.Symbol.values[0]].TradeDate.unique())
    last_trade_date = dates[-1]
    idx = np.where(dates==data['TradeDate'].values)[0][0]
    
    
    multiplyer = 1   
    if data.CallPut.values[0] == "p":
        multiplyer = -1
    flag = 0
    
    for j in range(hold):
        
        if dates[idx+j] == dates[-1]:
            break
        strike = data.AdjStrike.values[0]
        spot_start = data.AdjSpot.values[0]
        spot = df[df.TradeDate==dates[idx+j]]['AdjSpot'].iloc[0]
        next_spot = df.loc[df['TradeDate'] == dates[idx+j+1],'AdjSpot'].iloc[0]
        exp_dt = data.ExpiryDate.values[0]
            
        if dates[idx+j] not in df_iv.TradeDate.to_list() and dates[idx+j]<data.ExpiryDate.values[0]:
            if j == 0:

                delta = data['Delta'].values[0]
                px = (data['AskPrice'].values[0]+data['BidPrice'].values[0])/2
            else: 

                px = nextpx                
                delta = nextdelta
        else:
            delta = df_iv[df_iv.TradeDate==dates[idx+j]]['Delta'].iloc[0]
            px = (df_iv[df_iv.TradeDate==dates[idx+j]]['AskPrice'].iloc[0]+df_iv[df_iv.TradeDate==dates[idx+j]]['BidPrice'].iloc[0])/2     
        print(data.ExpiryDate.values[0])
        if dates[idx+j+1] not in df_iv.TradeDate.to_list() and dates[idx+j+1]<data.ExpiryDate.values[0]: 

            print(f'option with exp date {exp_dt} and strike  {strike}  not traded on {dates[idx+j+1]}')
            # delta = data.Delta.values[0]
            nextpx,nextdelta = get_premium(df,data.CallPut.values[0],data.AdjStrike.values[0],dates[idx+j+1],data.ExpiryDate.values[0],interpolator=interpolator)
                    
            f1 =1
             
        
        elif dates[idx+j+1]<data.ExpiryDate.values[0]:
        
            nextpx = (df_iv[df_iv.TradeDate==dates[idx+j+1]]['AskPrice'].values[0]+df_iv[df_iv.TradeDate==dates[idx+j+1]]['BidPrice'].values[0])/2
            nextdelta = df_iv[df_iv.TradeDate==dates[idx+j+1]]['Delta'].values[0]
            
                
        else:
                 
            nextpx = 0
            nextdelta = 0
                 
        if dates[idx+j+1]<= data.ExpiryDate.values[0]:
            # next_date_optpx = (df_iv[df_iv.TradeDate==dates[idx+j+1]]['AskPrice'].values[0]+df_iv[df_iv.TradeDate==dates[idx+j+1]]['BidPrice'].values[0])/2
            pnl =  (nextpx-px)/px
        else:
            flag =1
            pnl = (max(multiplyer*(data.ExpirySpot.values[0]-strike),0)-px)/px
        pnl = mt*pnl    

            # to be reviewed
            # elif j==hold-1:
            #     OptPx.append(OptPx[-1])
            #     OptDelta.append(OptDelta[-1])
                
            #     SpotPct.append(SpotPct[-1])
            #     if TradeDate[-1]<= data.ExpiryDate:
            #         spot = df.loc[df['TradeDate'] == TradeDate[-1],'Spot'].values[0]
            #         pnl = max(multiplyer*(spot-StrikeBot[-1]),0)-OptPx[-1]
            #     else:
            #         pnl = max(multiplyer*(data.ExpirtSpot-StrikeBot[-1]),0)-OptPx[-1]
        SpotPct.append((next_spot - spot)/spot)

        OptDelta.append(delta)         
        Spot.append(spot)          
        OptPxBot.append(px)
        OptPxTrade.append(nextpx)
        Exp.append(data.ExpiryDate.values[0])
        BotOn.append(data.TradeDate.values[0])
        TradeDate.append(dates[idx+j+1])
        SpotStart.append(spot_start)
        StrikeBot.append(strike)
        SpotExp.append(data.ExpirySpot.values[0])
        TradeStart.append(dates[idx+j])
        OptPnl.append(pnl)
        Synth.append(f1)
        f1= 0
        if TradeDate[-1] == last_trade_date:

            flag =1        


        if flag:
             
             break
        
    pnl_frame = pd.DataFrame({'BotOn':BotOn,'Flag':Synth,'TradeDate':TradeDate,'Exp':Exp,'StrikeBot':StrikeBot,'SpotStart':SpotStart,
                              'Spot':Spot,'SpotExp':SpotExp, 'OptPxBot':OptPxBot,'OptPxTrade':OptPxTrade,'OptDelta':OptDelta,
                              'SpotPct':SpotPct,'OptPnl':OptPnl,'TradeStart':TradeStart})
    
    return pnl_frame

In [ ]:
def gen_options_pnl(df,moneyness = 100, time_to_expiry = 1,callput = 'p',bot =1,hold = 1, buysell = 'buy',
                    value = 1,sizing = "notional",interpolator ='bicubic',pct = 1,contract_size =100,symbool='EV',start_date = None,end_date= None):
    capital = 10000000
    if buysell=='buy':
        mt =1
    else:
        mt=-1
    df_opt=extract_data(df,expiry_in_months=time_to_expiry,moneyness=moneyness,callput=callput,hold =hold,symbool=symbool,
                        start_date = start_date,end_date= end_date,bot=bot,interpolator = interpolator)
    df_opt['NextSpot'] = df_opt.Spot.shift(-1)
    df_opt['NextSpot'] = df_opt['NextSpot'].ffill()
    df_opt = df_opt.iloc[:-1]
    # df_opt['IV'] = (df.AskImpliedVolatility + df.BidImpliedVolatility)/2
    last_date = np.sort(df[df.Symbol == symbool].TradeDate.unique())[-1]
    # df_opt['delta_IV'] = df_opt.apply(lambda x:compute_delta_iv(x),axis =1)
   
    option_accumulator = []
    for i in range(df_opt.shape[0]):
        
        
        data = df_opt[df_opt.index==i]
        
        if data.TradeDate.values[0] == last_date: # redundant
            break
        pnl_frame = compute_pnl(data,hold,mt,interpolator=interpolator)
        option_accumulator.append(pnl_frame)
    df_op = pd.concat(option_accumulator, ignore_index=True)
        
    #??? correction here also
    if sizing == 'notional':
        df_op['OptPnlNotional'] = (df_op.OptPxBot*df_op.OptPnl/df_op.Spot)*value  # value no of options 
    if sizing == 'premium':
        df_op['OptPnlPremium'] = (df_op.OptPnl)*pct/100

    if sizing == 'contracts': 
        df_op['OptPnlContracts'] =df_op.OptPnl*df_op.OptPxBot*contract_size*value # value no of contracts
    # hold
    df_active_contracts  = (df_op.groupby('TradeStart').size().reset_index(name='ActiveOptions'))
    df_op ['NumOfContracts'] = df_op.apply(lambda x: compute_contracts(x,df_active_contracts,capital),axis=1)
    df_op = df_op.drop(columns =['TradeStart'])
    return df_op

In [ ]:
def wealth_computation(df,nav =1000,sizing ='notional',hold=1):
    if hold==1:
        if sizing =='notional':
            df['Wealth']  = nav*(1 + df['OptPnlNotional']).cumprod()
        elif sizing =='premium':
            #df['OptPnlPremium'] = df['OptPnlPremium'].replace([np.inf, -np.inf], 0,)
            df['Wealth']  = nav*(1 + df['OptPnlPremium']).cumprod()
            
        elif sizing == 'contracts':
            df['CumPnL'] = df['OptPnlContracts'].cumsum()
            df['Wealth'] = nav + df['CumPnL']
            # df['r_t'] = df['CumPnL'] / df['NAV'].shift(1)
            # df.loc[0,'r_t'] = df['CumPnL'].iloc[0]/nav
            # df['wealth'] = nav * (1 + df['r_t']).cumprod()
       
    else : 
        
        if sizing =='notional':
            agg_pnl = df.groupby(by='TradeDate').OptPnlNotional.sum()
            wealth  = nav*(1 + agg_pnl).cumprod()
            df = (pd.DataFrame({'AggrigatedPnl':agg_pnl,'Wealth':wealth})).reset_index()
        elif sizing =='premium':
            #df['OptPnlPremium'] = df['OptPnlPremium'].replace([np.inf, -np.inf], 0,)
            agg_pnl = df.groupby(by='TradeDate').OptPnlPremium.sum()
            wealth  = nav*(1 + agg_pnl).cumprod()
            df = (pd.DataFrame({'AggrigatedPnl':agg_pnl,'Wealth':wealth})).reset_index()
        elif sizing == 'contracts':
            agg_pnl = df.groupby(by='TradeDate').OptPnlContracts.sum()
            cumpnl = agg_pnl.cumsum()
            wealth = nav+cumpnl
            df = (pd.DataFrame({'AggrigatedPnl':agg_pnl,'CumPnl':cumpnl,'Wealth':wealth})).reset_index()
            
            # df['r_t'] = df['CumPnL'] / df['NAV'].shift(1)
            # df.loc[0,'r_t'] = df['CumPnL'].iloc[0]/nav
            # df['wealth'] = nav * (1 + df['r_t']).cumprod()
    return df

In [ ]:
df= df.drop_duplicates()

In [ ]:
np.sort(df_opt.days_to_expiry.unique())

In [ ]:
mn_110_12m_n = gen_options_pnl(df,moneyness=110, time_to_expiry=12,bot=3,callput='c',symbool='EV',value=1,sizing='notional',interpolator = 'linear',pct=3,start_date=20100331,hold=12)

In [ ]:
mn_110_12m_n[mn_110_12m_n.TradeDate ==20130830	]

In [ ]:
#linear
import matplotlib.pyplot as plt
w_df = wealth_computation(df=mn_110_12m_n,hold=12)
plt.plot(w_df.Wealth)

In [ ]:
mn_110_12m_pr = gen_options_pnl(df,moneyness=110, time_to_expiry=12,bot=3,callput='c',symbool='EV',value=1,sizing='premium',interpolator='linear',pct=3,start_date=20100331,hold=12)

In [ ]:
mn_110_12m_pr[mn_110_12m_pr.TradeDate==20140731].head(10)

In [ ]:
np.sort(df[df.TradeDate==20140731].AskPrice.unique()).min()

In [ ]:
# premium
w_pr = wealth_computation(df=mn_110_12m_pr,sizing='premium',hold=12)
print(w_pr.shape)
plt.plot(w_pr.Wealth)

In [ ]:
mn_110_12m_c = gen_options_pnl(df,moneyness=110, time_to_expiry=12,bot=3,callput='c',symbool='EV',value=1,sizing='contracts',interpolator='linear',pct=3,start_date=20100331,hold=12)

In [ ]:
# linear
c_pr = wealth_computation(df=mn_110_12m_c,sizing='contracts',hold=12)
print(c_pr.shape)
plt.plot(c_pr.Wealth)

In [ ]:
saving_dir = os.path.join('c:\\Users\\shyam\\Dp Lrn\\Options','Data')
with pd.ExcelWriter(os.path.join(saving_dir,'12m_110_b3_h12.xlsx'), engine="xlsxwriter") as writer:
    mn_110_12m_n.to_excel(writer, sheet_name="Notional", index=False)
    w_df.to_excel(writer, sheet_name="WealthNotional", index=False)
    mn_110_12m_pr.to_excel(writer, sheet_name="Premium", index=False)
    w_pr.to_excel(writer, sheet_name="WealthPremium", index=False)
    mn_110_12m_c.to_excel(writer, sheet_name="Contracts", index=False)
    c_pr.to_excel(writer, sheet_name="WealthContracts", index=False)

In [ ]:
if not os.path.exists(os.path.join('c:\\Users\\shyam\\Dp Lrn\\Options','Data','wealth_data_sp')):
    os.mkdir((os.path.join('c:\\Users\\shyam\\Dp Lrn\\Options','Data','wealth_data_sp')))

In [ ]:
saving_dir = os.path.join('c:\\Users\\shyam\\Dp Lrn\\Options','Data')

In [ ]:
mn_100_3m_c = gen_options_pnl(moneyness=110, time_to_expiry=3,callput='c',symbool='SP',sizing='notional',pct=3,buysell='buy')

In [ ]:
df.Symbol.unique()

In [ ]:
mn_100_1m_p = gen_options_pnl(moneyness=100, time_to_expiry=1,symbool='SP',pct=3)
mn_100_1m_p['wealth'] = 1000*(1 + mn_100_1m_p['OptPnlNotional']).cumprod()

In [ ]:
mn_100_1m_p.to_csv(os.path.join(saving_dir,'mn_100_1m_p.csv'))

In [ ]:
plt.plot(mn_100_1m_p.wealth)

In [ ]:
df_opt.shape

In [ ]:
dates = np.sort(df[df.Symbol == 'EV'].TradeDate.unique())
missing_dates = [date for date in dates if date not in mn_100_1m_p.BotOn.values]
missing_dates

In [ ]:
mn_100_1m_c = gen_options_pnl(moneyness=100, time_to_expiry=1,callput='c',symbool='SP')
mn_100_1m_c['wealth'] = 1000*(1 + mn_100_1m_c['OptPnlNotional']).cumprod()

In [ ]:
mn_100_1m_c.to_csv(os.path.join(saving_dir,'mn_100_1m_c.csv'))

In [ ]:
mn_110_1m_c = gen_options_pnl(moneyness=110, time_to_expiry=1,callput='c',symbool='SP')
mn_110_1m_c.shape

In [ ]:

cum_wlth_mn_110_1m_c_mn_90_1m_p = 1000*(1 + mn_110_1m_c['OptPnlNotional']+mn_90_1m_p['OptPnlNotional']).cumprod()

In [ ]:
plt.plot(cum_wlth_mn_110_1m_c_mn_90_1m_p)

In [ ]:
with pd.ExcelWriter(os.path.join(saving_dir,'1m_110c_90p.xlsx'), engine="xlsxwriter") as writer:
    mn_90_1m_p.to_excel(writer, sheet_name="mn_90_1m_p", index=False)
    mn_110_1m_c.to_excel(writer, sheet_name="mn_110_1m_c", index=False)

In [ ]:
cum_wlth_mn_110_3m_c_mn_90_3m_p = 1000*(1 + mn_110_3m_c['OptPnlNotional']+mn_90_3m_p['OptPnlNotional']).cumprod()

In [ ]:
plt.plot(cum_wlth_mn_110_3m_c_mn_90_3m_p)

In [ ]:
with pd.ExcelWriter(os.path.join(saving_dir,'3m_110c_90p.xlsx'), engine="xlsxwriter") as writer:
    mn_90_3m_p.to_excel(writer, sheet_name="mn_90_3m_p", index=False)
    mn_110_3m_c.to_excel(writer, sheet_name="mn_110_3m_c", index=False)